# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: project_metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "project_metadata.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16project_metadata.proto\x12\x10project_metadata\x1a\x0c\x63ommon.proto"L\n\x16ProjectMetadataRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t"\xc5\x01\n\x17ProjectMetadataResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x1a\n\x12\x63reated_at_seconds\x18\x05 \x01(\x03\x12\x18\n\x10\x63reated_at_nanos\x18\x06 \x01(\x05\x12\x1a\n\x12updated_at_seconds\x18\x07 \x01(\x03\x12\x18\n\x10updated_at_nanos\x18\x08 \x01(\x05"^\n\x1cProjectMetadataUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t"&\n\x18ProjectMetadataIdRequest\x12\n\n\x02id\x18\x01 \x01(\t"Z\n\x1bProjectMetadataListResponse\x12;\n\x08projects\x18\x01 \x03(\x0b\x32).project_metadata.ProjectMetadataResponse2\xe9\x03\n\x16ProjectMetadataService\x12\x64\n\rCreateProject\x12(.project_metadata.ProjectMetadataRequest\x1a).project_metadata.ProjectMetadataResponse\x12\x63\n\nGetProject\x12*.project_metadata.ProjectMetadataIdRequest\x1a).project_metadata.ProjectMetadataResponse\x12L\n\x0cListProjects\x12\r.common.Empty\x1a-.project_metadata.ProjectMetadataListResponse\x12j\n\rUpdateProject\x12..project_metadata.ProjectMetadataUpdateRequest\x1a).project_metadata.ProjectMetadataResponse\x12J\n\rDeleteProject\x12*.project_metadata.ProjectMetadataIdRequest\x1a\r.common.EmptyB2Z0github.com/example/fastapi-grpc/project_metadatab\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "project_metadata_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"Z0github.com/example/fastapi-grpc/project_metadata"
    )
    _globals["_PROJECTMETADATAREQUEST"]._serialized_start = 58
    _globals["_PROJECTMETADATAREQUEST"]._serialized_end = 134
    _globals["_PROJECTMETADATARESPONSE"]._serialized_start = 137
    _globals["_PROJECTMETADATARESPONSE"]._serialized_end = 334
    _globals["_PROJECTMETADATAUPDATEREQUEST"]._serialized_start = 336
    _globals["_PROJECTMETADATAUPDATEREQUEST"]._serialized_end = 430
    _globals["_PROJECTMETADATAIDREQUEST"]._serialized_start = 432
    _globals["_PROJECTMETADATAIDREQUEST"]._serialized_end = 470
    _globals["_PROJECTMETADATALISTRESPONSE"]._serialized_start = 472
    _globals["_PROJECTMETADATALISTRESPONSE"]._serialized_end = 562
    _globals["_PROJECTMETADATASERVICE"]._serialized_start = 565
    _globals["_PROJECTMETADATASERVICE"]._serialized_end = 1054
# @@protoc_insertion_point(module_scope)
