# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import common_pb2 as common__pb2
from . import project_metadata_pb2 as project__metadata__pb2

GRPC_GENERATED_VERSION = "1.78.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in project_metadata_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ProjectMetadataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProject = channel.unary_unary(
            "/project_metadata.ProjectMetadataService/CreateProject",
            request_serializer=project__metadata__pb2.ProjectMetadataRequest.SerializeToString,
            response_deserializer=project__metadata__pb2.ProjectMetadataResponse.FromString,
            _registered_method=True,
        )
        self.GetProject = channel.unary_unary(
            "/project_metadata.ProjectMetadataService/GetProject",
            request_serializer=project__metadata__pb2.ProjectMetadataIdRequest.SerializeToString,
            response_deserializer=project__metadata__pb2.ProjectMetadataResponse.FromString,
            _registered_method=True,
        )
        self.ListProjects = channel.unary_unary(
            "/project_metadata.ProjectMetadataService/ListProjects",
            request_serializer=common__pb2.Empty.SerializeToString,
            response_deserializer=project__metadata__pb2.ProjectMetadataListResponse.FromString,
            _registered_method=True,
        )
        self.UpdateProject = channel.unary_unary(
            "/project_metadata.ProjectMetadataService/UpdateProject",
            request_serializer=project__metadata__pb2.ProjectMetadataUpdateRequest.SerializeToString,
            response_deserializer=project__metadata__pb2.ProjectMetadataResponse.FromString,
            _registered_method=True,
        )
        self.DeleteProject = channel.unary_unary(
            "/project_metadata.ProjectMetadataService/DeleteProject",
            request_serializer=project__metadata__pb2.ProjectMetadataIdRequest.SerializeToString,
            response_deserializer=common__pb2.Empty.FromString,
            _registered_method=True,
        )


class ProjectMetadataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def UpdateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ProjectMetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateProject": grpc.unary_unary_rpc_method_handler(
            servicer.CreateProject,
            request_deserializer=project__metadata__pb2.ProjectMetadataRequest.FromString,
            response_serializer=project__metadata__pb2.ProjectMetadataResponse.SerializeToString,
        ),
        "GetProject": grpc.unary_unary_rpc_method_handler(
            servicer.GetProject,
            request_deserializer=project__metadata__pb2.ProjectMetadataIdRequest.FromString,
            response_serializer=project__metadata__pb2.ProjectMetadataResponse.SerializeToString,
        ),
        "ListProjects": grpc.unary_unary_rpc_method_handler(
            servicer.ListProjects,
            request_deserializer=common__pb2.Empty.FromString,
            response_serializer=project__metadata__pb2.ProjectMetadataListResponse.SerializeToString,
        ),
        "UpdateProject": grpc.unary_unary_rpc_method_handler(
            servicer.UpdateProject,
            request_deserializer=project__metadata__pb2.ProjectMetadataUpdateRequest.FromString,
            response_serializer=project__metadata__pb2.ProjectMetadataResponse.SerializeToString,
        ),
        "DeleteProject": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteProject,
            request_deserializer=project__metadata__pb2.ProjectMetadataIdRequest.FromString,
            response_serializer=common__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "project_metadata.ProjectMetadataService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "project_metadata.ProjectMetadataService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ProjectMetadataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProject(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/project_metadata.ProjectMetadataService/CreateProject",
            project__metadata__pb2.ProjectMetadataRequest.SerializeToString,
            project__metadata__pb2.ProjectMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetProject(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/project_metadata.ProjectMetadataService/GetProject",
            project__metadata__pb2.ProjectMetadataIdRequest.SerializeToString,
            project__metadata__pb2.ProjectMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListProjects(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/project_metadata.ProjectMetadataService/ListProjects",
            common__pb2.Empty.SerializeToString,
            project__metadata__pb2.ProjectMetadataListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def UpdateProject(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/project_metadata.ProjectMetadataService/UpdateProject",
            project__metadata__pb2.ProjectMetadataUpdateRequest.SerializeToString,
            project__metadata__pb2.ProjectMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteProject(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/project_metadata.ProjectMetadataService/DeleteProject",
            project__metadata__pb2.ProjectMetadataIdRequest.SerializeToString,
            common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
